### ISSUE TITLE
Nicehashminer mod by DillonN

### ISSUE THREAD

**Issue by imrecsoka** [DillonN/NiceHashMiner#1]
Hi, i have not tried this yet , but i guess i just extract and run it like the normal vanilla version right?
Do i really have to follow the instructions about manually typing a value and then mining?
Oh , is this AMD friendly or is this more for nVidia cards?
I have AMD because i was told to buy AMD which is what i did so now i hope there is hope for me.

**Comment by DillonN** [comment]
Yes for the release https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.5.14-Extra it works exactly like the vanilla version

If you're referring to the intensity tuning for dual mining, no you don't have to do it. But if you have a bigger card (e.g. 1080 Ti) you can get serious gains (I got 60% on the DaggerSia)

**Comment by ramius86** [comment]
should be nice create a template with some value about amd and nvidia card, just started benchmarking with 1.7.5.14 with 7 1070 strix and will update this post with my dcri sweetspot, if I will ever find one

**Comment by imrecsoka** [comment]
Okay well i am learning and this is all rocket science to me , i will run and bench it tonight to see what muscle gain i get. I am not sure what the tweaks you mentioned, but i will just do the vanilla practice , which is run the benchmark and thats it right ?

I have 2 RX470's so i dont know if doing what you did describe is worth it ? if it is say 10 mega hashes more than i will so yah.... if i dont come right can we please teamview or share desktop?
Thanks

**Comment by DillonN** [comment]
@ramius86 Good idea, [I've added one](https://github.com/DillonN/NiceHashMiner/blob/new/IntensitiesForClaymoreDual.MD) with the intensities I found on my cards for Sia. Let me know when you find a good spot and I'll add it.

@imrecsoka If you are using 470s I'd bet sticking with the default values would be best. So just run it like the vanilla version!

**Comment by DillonN** [comment]
If anyone has weird behaviour with the EWBF benchmark, download the newest version there was a bug

**Comment by imrecsoka** [comment]
No man , this is is already crashing for me, i only downloaded "NHM-1.7.5.14-Extra"
and then ran the nihashminer.exe and it is saying nvm dll or something is missing.

**Comment by DillonN** [comment]
What exactly does it say? And what OS are you using

**Comment by imrecsoka** [comment]
Windows 7 Ultimate
![image](https://user-images.githubusercontent.com/25494601/27349995-5d327dc4-55f9-11e7-95fd-fca4ac512543.png)

**Comment by DillonN** [comment]
You can ignore the nvml.dll warning that's just because you don't have any NVIDIA drivers installed

The missing AMD cards is because you don't have [Visual C++ 2017](https://go.microsoft.com/fwlink/?LinkId=746572) installed, my fault I should have made a notice when I upgraded the project

I will fix both problems in a new release, give me 10 minutes

**Comment by DillonN** [comment]
Here https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.5.16

**Comment by imrecsoka** [comment]
Wait so i will be fine with 2013 an 2015 installed , i dont need 2017 right?
will i break my machine if i install 2017 ?

**Comment by DillonN** [comment]
Yes I back pedaled the upgrade to 2017, you shouldn't have to install anything
