### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by GongoloMin** [DillonN/NiceHashMiner#14]
Version 1.7.5.19, windows 10, four cards (3 nvidia, 1 amd).
I started precise benchmarks at the first run.
While on GTX1080ti, looking at Afterburner I can see GPU Power use on Radeon card instead: in fact, it shows 22 MH/s for DaggerHashimoto (Claymore).
DaggerHashimoto (ethminer) benchmark is correct.

**Comment by DillonN** [comment]
This is a known issue

#7
