### ISSUE TITLE
Adding extra launch parameter to EWBF miner via "Extra Launch Parameters" causes miner to not even start

### ISSUE THREAD

**Issue by stevo63** [DillonN/NiceHashMiner#18]
https://github.com/nanopool/ewbf-miner/issues/15

Possible solution:
https://github.com/gacopl/NiceHashMiner/issues/10

**Comment by DillonN** [comment]
Hey sorry I've been away for the weekend. Someone brought my attention to this on Reddit and I will hopefully have a fix for it out in the next update.

**Comment by DillonN** [comment]
Fixed in commit eb7b06d, will be in next update

**Comment by DillonN** [comment]
https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.6.2
