### ISSUE TITLE
Feature request please!

### ISSUE THREAD

**Issue by imrecsoka** [DillonN/NiceHashMiner#2]
Will you be able to add multithread download , say 2 threads for the downloading of the miners.
Its frustrating when downloading the miners and it hangs, and its not just me with a crapy 10 meg ADSL line connection to the Github servers.

![image](https://user-images.githubusercontent.com/25494601/27352888-8955e888-5602-11e7-8a59-9243e3fe3c37.png)
  a download which just hung

**Comment by DillonN** [comment]
The hanging of downloads is a GitHub server side problem I believe, since if you download the files directly from Chrome it can hang even. I've been thinking of a way to overcome this, which probably involves hosting the bin files somewhere else

**Comment by imrecsoka** [comment]
yeh because im sure NiceHash Miner projects are not the only massive files on the github servers

**Comment by DillonN** [comment]
Yeah I have gigabit internet and it's still pretty bad. It'd be ideal if GitHub could fix it

**Comment by DillonN** [comment]
I've rewritten the download logic that drastically improves the experience. Hangs are identified within 10 seconds and downloading is resumed. It is also multithreaded and should make better use of available bandwidth

e9626dd

Will put it in the next release (later tonight or tomorrow). Hopefully this fixes for you too!

**Comment by DillonN** [comment]
https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.6.0
