### ISSUE TITLE
Request addition of Sia (non-dual)

### ISSUE THREAD

**Issue by malventano** [DillonN/NiceHashMiner#3]
Request addition of ccminer_sia. For quick reference, it's part of this existing mod: https://github.com/gacopl/NiceHashMiner/releases/tag/1.7.5.13-gaco-mod

**Comment by DillonN** [comment]
I can do that, when I tried it was not profitable. Let me check into it

**Comment by malventano** [comment]
Understood. So long as the hash rate is as expected, it is good to have it available in case Sia rates spike.

**Comment by DillonN** [comment]
Now added

https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.5.17
