### ISSUE TITLE
secondary benchmark speed clearing issue

### ISSUE THREAD

**Issue by malventano** [DillonN/NiceHashMiner#4]
After clearing algorithm speeds (from either benchmarks or devices/algorithms), then going into settings to tweak launch parameters, note that previous secondary benchmark speeds reappear as the various algos are selected. Appears secondary benchmark variables are not being properly cleared when requested.

**Comment by DillonN** [comment]
Nice catch, was just a small oversight

https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.5.17
