### ISSUE TITLE
GUI: main screen displayed rates cuts off long entries (dual mining)

### ISSUE THREAD

**Issue by malventano** [DillonN/NiceHashMiner#6]
The 'Rate' title superimposes over the current dual rate being mined. Recommend taking some of the white space out of the fields after Rate (between BTC/Day and USD/Day), shifting it over to the right a tad, to mitigate the issue.

**Comment by DillonN** [comment]
Something I've had in the back of my mind for a while to fix

https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.5.17
