### ISSUE TITLE
ClaymoreDual does not mine on correct device when both AMD and NVIDIA cards present

### ISSUE THREAD

**Issue by DillonN** [DillonN/NiceHashMiner#7]
Passed by me since I don't have mixed cards in a rig. I'll look into it

**Comment by CreamyG31337** [comment]
I can duplicate this issue and I don't mind testing this for you. I know c# but I don't think I can see the bug without installing visual studio, compiling, and debugging this. Maybe you should add a test project to this and try to reproduce it that way?

**Comment by justsomedudeonthenet** [comment]
I am also able to replicate this issue - and unable to benchmark any of the dual algorithms because of it.

**Comment by justsomedudeonthenet** [comment]
Here is the relevant portion of the logs:
`
14:45:33:202	2a54	args: -di 0 -epool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -ewal <censored> -mport 127.0.0.1:4004 -esm 3 -epsw x -allpools 1 -benchmark 1 
14:45:33:203	2a54	
14:45:33:203	2a54	ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
14:45:33:203	2a54	º      Claymore's Dual ETH + DCR/SC/LBC/PASC GPU Miner v9.5      º
14:45:33:203	2a54	ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼
14:45:33:204	2a54	
14:45:34:476	2a54	OpenCL platform: NVIDIA CUDA
14:45:34:476	2a54	OpenCL platform: AMD Accelerated Parallel Processing
14:45:34:478	2a54	OpenCL initializing...

14:45:34:478	2a54	AMD Cards available: 1 
14:45:34:478	2a54	GPU #0: Bonaire, 2048 MB available, 14 compute units
14:45:34:478	2a54	POOL/SOLO version
14:45:34:479	2a54	b351 
14:45:34:479	2a54	Platform: Windows
14:45:34:519	2a54	start building OpenCL program for GPU 0...
14:45:40:393	2a54	done
14:45:40:611	2a54	GPU #0: set -etha as 1 (ETH algo for slow cards)
14:45:40:764	2a54	CUDA initializing...

14:45:40:764	2a54	NVIDIA Cards available: 1 
14:45:40:764	2a54	CUDA Driver Version/Runtime Version: 8.0/8.0
14:45:40:764	2a54	No NVIDIA cards in the list.
14:45:40:765	2a54	Total cards: 1 
14:45:43:657	2a54	No NVIDIA cards in the list, NVML library will not be used.
14:45:43:762	2a54	

14:45:43:762	2a54	
BENCHMARK MODE!

14:45:43:765	32c8	Setting DAG epoch #125...
14:45:45:088	32c8	Setting DAG epoch #125 for GPU0
14:45:45:088	32c8	Create GPU buffer for GPU0
14:45:45:088	32c8	GPU0 - OpenCL error -61 - cannot allocate big buffer for DAG. Check readme.txt for possible solutions.
`

NHM shows CPU#1 as my GTX1080, and GPU#2 as Radeon R7 200 Series
Claymore lists GPU0 as the Radeon and GPU1 as the Nvidia GTX 1080.

My guess would be it's always enumerating AMD cards first, then Nvidia cards.  So the AMD cards will always be first in it's list?

**Comment by DillonN** [comment]
@justsomedudeonthenet yes the problem is with the device indexes. ClaymoreDual is the only miner currently that works for both AMD and NVIDIA, so there is no logic (yet) to select between the two.

I can't test if your intuition is right on CD increasing the NV indexes by the amount of AMD cards available, but I've applied a fix that will consider this in NHM. If someone with both AMD/NV cards can test this I'd appreciate it. Please try running CD and check the logs for some lines that are tagged with `ClaymoreDualIndexing` and let me know what they say, as well as if CD mines on the correct cards.

[NHM-CDFix.zip](https://github.com/DillonN/NiceHashMiner/files/1103438/NHM-CDFix.zip)

**Comment by CreamyG31337** [comment]
I think the fix is working, thanks for figuring it out! I'll post the logs later.

**Comment by CreamyG31337** [comment]
[temp log.txt](https://github.com/DillonN/NiceHashMiner/files/1103514/temp.log.txt)

**Comment by CreamyG31337** [comment]
![image](https://user-images.githubusercontent.com/11222932/27562763-545317ae-5a8b-11e7-995e-dddb29968097.png)

**Comment by DillonN** [comment]
Nice, from the logs and what you said it looks like the fix is working. I will wait for someone else to chime in just to make sure it didn't break anything for AMD&NV users, but looks like this will be in the next release

**Comment by CreamyG31337** [comment]
Sure. The benchmarking worked for all the cards I tried individually, and I tried enabling different cards and didn't see any issues that way either. Hopefully it was that easy :)

**Comment by justsomedudeonthenet** [comment]
I will be able to test it tomorrow and let you know how it works on my system.

**Comment by DillonN** [comment]
https://github.com/DillonN/NiceHashMiner/releases/tag/1.7.6.2 live in the newest version

Will leave this issue open for the time being

**Comment by justsomedudeonthenet** [comment]
Just tried 1.7.6.3

Benchmarks work, and running the dual miner for mining works.  Chooses the correct card in both cases.

Looks like this fixed it.  Thanks!

**Comment by DillonN** [comment]
Looks like no one is having trouble anymore, I'll close this
